name: 'Process coverage data'
description: 'Process coverage data'
runs:
  using: "composite"
  steps:
      - name: "Process coverage data"
        run:  pkg-ci-scripts/gather-coverage.sh
        shell: bash
